#ifndef DIALOGTYPE_H
#define DIALOGTYPE_H
enum DialogType
{
    AREA_SELECTOR=0,
    SCREEN_BUTTONS_DETECTOR=1,
    COORDINATES_SELECTOR=2,
    SHELL_COMMAND_DIALOG=3
};
#endif // DIALOGTYPE_H
